#!/usr/bin/env php

<?php
/*
 * This file is part of Phantastic.
 *
 * Phantastic is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Phantastic is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Phantastic.  If not, see <http://www.gnu.org/licenses/>.
 */

include('lib/phpmarkdown/markdown.php');

//TODO: Créer une classe s’occupant des URL
include_once('class/Path.php');
include_once('class/Parser.php');
include_once('class/Config.php');
include_once('class/File.php');
include_once('class/Tag.php');
include_once('class/Category.php');
include_once('class/History.php');
include_once('class/Template.php');
include_once('class/Generator.php');
include_once('class/Options.php');
include_once('class/Arg.php');
include_once('class/Server.php');
include_once('class/App.php');


//var_dump(__DIR__);

$phantastic = new Malenki\Phantastic\App();
$phantastic->setOpt();
$phantastic->getOpt();
$phantastic->run();



